version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Asia/Riyadh"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
