"use client";
import { useState } from "react";import { Archive, ArrowLeft, Bell, Check, Clipboard, Copy, FileJson, FileText, Grid2X2, Link2, LocateFixed, MapPin, Menu, MessageCircle, Package, Plus, Search, Settings2, ShoppingBag, Store, Truck, Users, X } from "lucide-react";import { Button } from "@/components/ui/button";import { Input } from "@/components/ui/input";import { Textarea } from "@/components/ui/textarea";import { Switch } from "@/components/ui/switch";
const initialProducts = [ { id: "p1", name: "ورقيات مشكلة", unit: "حزمة", price: 8, status: "وصل اليوم" }, { id: "p2", name: "طماطم بلدية", unit: "كيلو", price: 7, status: "متوفر" }, { id: "p3", name: "سلة فواكه الموسم", unit: "سلة", price: 38, status: "متوفر" }, { id: "p4", name: "خيار طازج", unit: "كيلو", price: 6, status: "غير متوفر" },];
const initialOrders = [ { id: "#K-1042", name: "نورة العتيبي", items: "ورقيات × 2 · طماطم × 1", total: "23 ر.س", status: "جديدة", service: "توصيل" }, { id: "#K-1041", name: "سارة محمد", items: "سلة فواكه · خيار", total: "44 ر.س", status: "جديدة", service: "استلام" }, { id: "#K-1040", name: "ريم خالد", items: "طماطم × 3 · نعناع", total: "25 ر.س", status: "مستلَمة", service: "يجيك" },];
type Section = "overview" | "orders" | "products" | "location" | "payment" | "tools";
export default function KhudaranaOperations() { const [section, setSection] = useState<Section>("overview"); const [orders, setOrders] = useState(initialOrders); const [products, setProducts] = useState(initialProducts); const [receiving, setReceiving] = useState(true); const [sellerMode, setSellerMode] = useState("متجول"); const [notice, setNotice] = useState(""); const [flash, setFlash] = useState("وصلت خضار الصباح — الكمية محدودة"); const [chatOpen, setChatOpen] = useState(false);
 function notify(message: string) {    setNotice(message);    window.setTimeout(() => setNotice(""), 2200); }
 function completeOrder(id: string) {    setOrders((current) =>      current.map((order) =>        order.id === id ? { ...order, status: "مستلَمة" } : order,      ),    );    notify(`تم استلام الطلب ${id}`); }
 function toggleProduct(id: string, status: string) {    setProducts((current) =>      current.map((product) =>        product.id === id ? { ...product, status } : product,      ),    );    notify(`تم تحديث حالة ${status}`); }
 const nav: {    key: Section;    label: string;    icon: typeof Store; }[] = [    { key: "overview", label: "نظرة عامة", icon: Store },    { key: "orders", label: "الطلبات", icon: ShoppingBag },    { key: "products", label: "المنتجات والمخزون", icon: Package },    { key: "location", label: "الموقع والساعات", icon: MapPin },    { key: "payment", label: "الدفع المباشر", icon: Clipboard },    { key: "tools", label: "أدوات المشاركة", icon: Grid2X2 }, ];
 return (    <main dir="rtl" className="min-h-dvh bg-[#f4f1e8] text-[#22332b]">      <div className="grid min-h-dvh lg:grid-cols-[250px_minmax(0,1fr)]">        <aside className="hidden border-l border-[#dfe4d6] bg-[#fffdf5] p-5 lg:flex lg:flex-col">          <div className="flex items-center gap-3 border-b border-[#dfe4d6] pb-6">            <div className="flex size-10 items-center justify-center rounded-full bg-[#eaf1e4] text-[#4a7b46]">              <KhudaranaMark size="sm" />            </div>            <div>              <p className="text-[10px] font-bold tracking-[0.2em] text-[#5b7d48]">                مساحة التشغيل              </p>              <p className="text-lg font-black">خضارنا1</p>            </div>          </div>
          <div className="mt-6 rounded-2xl bg-[#20352b] p-4 text-white">            <p className="text-xs text-[#cbe4b8]">حالة البائع</p>            <p className="mt-2 text-lg font-black">{sellerMode}</p>            <p className="mt-1 text-[11px] text-[#c4dcc1]">              {receiving ? "يستقبل الطلبات الآن" : "الاستقبال متوقف"}            </p>          </div>
          <nav className="mt-7 flex-1 flex-col gap-1">            {nav.map(({ key, label, icon: Icon }) => (              <Button                key={key}                onClick={() => setSection(key)}                className={`h-11 justify-start gap-3 rounded-xl px-3 text-sm font-bold shadow-none ${                  section === key                    ? "bg-[#eaf1e4] text-[#3f6d3c] hover:bg-[#dfeeda]"                    : "bg-transparent text-[#6d7b6d] hover:bg-[#f0f5ec]"                }`}              >                <Icon size={17} />                {label}                {key === "orders" && (                  <span className="mr-auto flex size-5 items-center justify-center rounded-full bg-[#4f813f] text-[10px] text-white">                    {orders.filter((order) => order.status === "جديدة").length}                  </span>                )}              </Button>            ))}
            <div className="my-4 h-px bg-[#dfe4d6]" />
            <Button              onClick={() => notify("تم فتح الدليل المدمج")}              className="h-11 justify-start gap-3 rounded-xl bg-transparent px-3 text-sm font-bold text-[#6d7b6d] shadow-none hover:bg-[#f0f5ec]"            >              <FileText size={17} />              دليل الاستخدام            </Button>
            <Button              onClick={() => notify("تم فتح الأرشيف")}              className="h-11 justify-start gap-3 rounded-xl bg-transparent px-3 text-sm font-bold text-[#6d7b6d] shadow-none hover:bg-[#f0f5ec]"            >              <Archive size={17} />              أرشيف الطلبات            </Button>          </nav>
          <a            href="/khudarana"            className="flex items-center gap-3 border-t border-[#dfe4d6] px-3 pt-5 text-sm font-bold text-[#6d7b6d] hover:text-[#3f6d3c]"          >            <Store size={17} />            صفحة العميل            <ArrowLeft size={14} className="mr-auto" />          </a>        </aside>
        <section className="min-w-0">          <header className="flex min-h-[78px] items-center justify-between border-b border-[#dfe4d6] bg-[#fffdf5]/90 px-4 backdrop-blur-sm sm:px-8">            <div className="flex items-center gap-3">              <Button className="size-10 rounded-full bg-[#eaf1e4] p-0 text-[#426d42] shadow-none lg:hidden">                <Menu size={18} />              </Button>
              <div>                <p className="text-xs font-bold text-[#849284]">ملخص اليوم</p>                <h1 className="mt-1 text-xl font-black text-[#20352b] sm:text-2xl">                  إدارة خضارنا1                </h1>              </div>            </div>
            <div className="flex items-center gap-2">              <Button                onClick={() => setReceiving((value) => !value)}                className="hidden items-center gap-2 rounded-full border-[#d4dfcc] bg-white px-3 py-2 text-xs font-bold text-[#5f705f] shadow-none hover:bg-[#f0f5ec] sm:flex"              >                <span                  className={`size-2 rounded-full ${                    receiving ? "bg-[#3d9a6c]" : "bg-[#c56c5c]"                  }`}                />                {receiving ? "يستقبل الطلبات" : "متوقف مؤقتاً"}              </Button>
              <Button                onClick={() => notify("لا توجد تنبيهات جديدة")}                aria-label="التنبيهات"                className="size-10 rounded-full border-[#dfe4d6] bg-white p-0 text-[#637263] shadow-none hover:bg-[#f0f5ec]"              >                <Bell size={17} />              </Button>
              <div className="flex size-10 items-center justify-center rounded-full bg-[#3f7440] text-sm font-black text-white">                <KhudaranaMark inverse size="sm" />              </div>            </div>          </header>
          <div className="p-4 sm:p-8 lg:p-10">            <div className="mx-auto max-w-[1420px]">              {section === "overview" && (                <Overview                  orders={orders}                  products={products}                  receiving={receiving}                  sellerMode={sellerMode}                  setSellerMode={setSellerMode}                  onSection={setSection}                  onNotify={notify}                  onToggle={() => setReceiving((value) => !value)}                />              )}
              {section === "orders" && (                <Orders                  orders={orders}                  onComplete={completeOrder}                  onNotify={notify}                  onChat={() => setChatOpen(true)}                />              )}
              {section === "products" && (                <Products                  products={products}                  onToggle={toggleProduct}                  onNotify={notify}                />              )}
              {section === "location" && (                <Location                  sellerMode={sellerMode}                  setSellerMode={setSellerMode}                  onNotify={notify}                />              )}
              {section === "payment" && <Payment onNotify={notify} />}
              {section === "tools" && (           <Tools                  flash={flash}                  setFlash={setFlash}                  onNotify={notify}                />              )}            </div>          </div>        </section>      </div>
      {chatOpen && (        <Chat          onClose={() => setChatOpen(false)}          onNotify={notify}        />      )}
      {notice && (        <div className="fixed bottom-6 right-4 z-50 flex items-center gap-2 rounded-full bg-[#20352b] px-5 py-3 text-sm font-bold text-white shadow-xl sm:right-8">          <Check size={16} className="text-[#ce8bc]" />          {notice}        </div>      )}    </main> );}
function Overview({ orders, products, receiving, sellerMode, setSellerMode, onSection, onNotify, onToggle,}: { orders: typeof initialOrders; products: typeof initialProducts; receiving: boolean; sellerMode: string; setSellerMode: (value: string) => void; onSection: (value: Section) => void; onNotify: (value: string) => void; onToggle: () => void;}) { return (    <>      <div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end">        <div>          <p className="text-xs font-bold tracking-[0.16em] text-[#5b7d48]">            لوحة اليوم          </p>          <h2 className="mt-2 text-3xl font-black tracking-[-0.05em] text-[#20352b] sm:text-4xl">            رفك، طلباتك، وموقعك — واضحين          </h2>          <p className="mt-2 max-w-2xl text-sm leading-6 text-[#758374]">            خضارنا1 يعمل بنفس سرعة السوق: شوف الجديد، استلم الطلب، وخلّ العميل            يعرف أين أنت.          </p>        </div>
        <div className="flex flex-wrap gap-2">          <a            href="/khudarana"            className="inline-flex h-11 items-center gap-2 rounded-xl border-[#d4dfcc] bg-[#fffdf5] px-4 text-sm font-bold text-[#5f705f] hover:bg-[#eef4e9]"          >            معاينة المتجر            <ArrowLeft size={15} />          </a>
          <Button            onClick={onToggle}            className={`h-11 rounded-xl px-4 text-sm font-black shadow-none ${              receiving                ? "bg-[#3f7440] text-white hover:bg-[#356436]"                : "bg-[#b76558] text-white hover:bg-[#9f554c]"            }`}          >            {receiving ? "إيقاف استقبال الطلبات" : "تشغيل الاستقبال"}          </Button>        </div>      </div>
      <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4">        <Metric          label="طلبات جديدة"          value={String(orders.filter((order) => order.status === "جديدة").length)}          hint="تحتاج استلام"          tone="green"        />        <Metric          label="حضور مباشر"          value="7"          hint="متصفحين الآن"          tone="blue"        />        <Metric          label="أصناف وصلَت اليوم"          value={String(            products.filter((product) => product.status === "وصل اليوم").length,          )}          hint="ميّزها للعميل"          tone="gold"        />        <Metric          label="إجمالي اليوم"          value="92"          hint="ر.س"          tone="olive"        />      </div>
      <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(340px,0.8fr)]">        <section className="rounded-2xl border-[#dfe4d6] bg-[#fffdf5] p-5">          <div className="flex items-center justify-between">            <div>              <p className="text-xs font-bold tracking-[0.13em] text-[#5b7d48]">                الطلبات الجديدة              </p>              <h3 className="mt-1 text-lg font-black text-[#20352b]">                استلمها قبل أن تبرد              </h3>            </div>
            <Button              onClick={() => onSection("orders")}              className="h-9 rounded-full bg-transparent px-3 text-xs font-black text-[#4f813f] shadow-none hover:bg-[#eef4e9]"            >              كل الطلبات              <ArrowLeft size={14} />            </Button>          </div>
          <div className="mt-5 space-y-3">            {orders.slice(0, 2).map((order) => (              <div                key={order.id}                className="flex flex-col gap-3 rounded-xl border-[#dfe7d9] bg-white p-4 sm:flex-row sm:items-center"              >                <div className="min-w-0 flex-1">                  <div className="flex items-center gap-2">                    <span className="text-xs font-black text-[#4f813f]">                      {order.id}                    </span>                    <span className="rounded-full bg-[#eaf1e4] px-2 py-1 text-[10px] font-black text-[#4f813f]">                      {order.service}                    </span>                  </div>
                  <p className="mt-1 font-black text-[#20352b]">{order.name}</p>                  <p className="mt-1 truncate text-xs text-[#849284]">                    {order.items}                  </p>                </div>
                <div className="flex items-center justify-between gap-3">                  <span className="font-black text-[#4f813f]">                    {order.total}                  </span>                  <Button                    onClick={() => onNotify(`تم استلام ${order.id}`)}                    className="h-9 rounded-lg bg-[#3f7440] px-3 text-xs font-black text-white shadow-none hover:bg-[#356436]"                  >                    استلام                  </Button>                </div>              </div>            ))}          </div>        </section>
        <section className="rounded-2xl bg-[#20352b] p-5 text-white">          <div className="flex items-center justify-between">            <div>              <p className="text-xs font-bold tracking-[0.13em] text-[#cbe4b8]">                البائع المتجول              </p>              <h3 className="mt-1 text-lg font-black">تبّع الاقتراب</h3>            </div>
            <LocateFixed size={21} className="text-[#cbe4b8]" />          </div>
          <div className="mt-5 flex items-center gap-3 rounded-xl bg-white/10 p-4">            <span className="flex size-10 items-center justify-center rounded-full bg-[#cbe4b8] text-[#315534]">              <MapPin size={18} />            </span>
            <div>              <p className="text-sm font-black">                {sellerMode === "متجول" ? "متجول الآن" : "نقطة ثابتة"}              </p>              <p className="mt-1 text-xs text-[#c4dcc1]">                آخر تحديث منذ دقيقتين              </p>            </div>          </div>
          <Button            onClick={() => onSection("location")}            className="mt-4 h-10 w-full rounded-xl bg-[#d7e9c9] text-xs font-black text-[#27472c] shadow-none hover:bg-white"          >            إدارة الموقع والساعات            <ArrowLeft size={14} />          </Button>        </section>      </div>
      <section className="mt-6 rounded-2xl border-[#dfe4d6] bg-[#fffdf5] p-5">        <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">          <div>            <p className="text-xs font-bold tracking-[0.13em] text-[#5b7d48]">              عرض الفلاش            </p>            <h3 className="mt-1 text-lg font-black text-[#20352b]">              {flashPreview()}            </h3>            <p className="mt-1 text-sm text-[#758374]">              يظهر مباشرة أعلى صفحة العميل.            </p>          </div>
          <Button            onClick={() => onNotify("تم فتح محرر العرض الفلاش")}            className="h-10 rounded-xl border-[#d4dfcc] bg-white text-xs font-black text-[#4f813f] shadow-none hover:bg-[#eef4e9]"          >            تحرير العرض            <ArrowLeft size={14} />          </Button>        </div>      </section>    </> );
 function flashPreview() {    return "وصلت خضار الصباح — الكمية محدودة"; }}
function Orders({ orders, onComplete, onNotify, onChat,}: { orders: typeof initialOrders; onComplete: (id: string) => void; onNotify: (value: string) => void; onChat: () => void;}) { return (    <>      <PageHeading        eyebrow="الطلبات"        title="مساران واضحان، ولا طلب يضيع"        copy="استلمي التذكرة، تواصلي مع العميل، ثم أنهِيها عندما يخرج الطلب."        action={          <Button            onClick={() => onNotify("تم فتح بحث الطلبات")}            className="h-10 rounded-xl border-[#d4dfcc] bg-[#fffdf5] px-4 text-xs font-bold text-[#5f705f] shadow-none hover:bg-[#eef4e9]"          >            <Search size={15} />            بحث          </Button>        }      />
      <div className="mt-7 grid gap-5 lg:grid-cols-2">        <OrderLane          title="جديدة"          items={orders.filter((order) => order.status === "جديدة")}          onComplete={onComplete}          onNotify={onNotify}          onChat={onChat}        />        <OrderLane          title="مستلَمة"          items={orders.filter((order) => order.status === "مستلَمة")}          onComplete={onComplete}          onNotify={onNotify}          onChat={onChat}        />      </div>
      <section className="mt-5 rounded-2xl border-[#dfe4d6] bg-[#fffdf5] p-5">        <div className="flex items-center justify-between">          <div>            <h3 className="font-black text-[#20352b]">أرشيف الطلبات</h3>            <p className="mt-1 text-xs text-[#849284]">              احتفظي بنسخة من الطلبات عند الحاجة.            </p>          </div>
          <Button            onClick={() => onNotify("تم تجهيز ملف JSON للتصدير")}            className="h-10 rounded-xl border-[#d4dfcc] bg-white text-xs font-black text-[#4f813f] shadow-none hover:bg-[#eef4e9]"          >            <FileJson size={15} />            تصدير JSON          </Button>        </div>      </section>    </> );}
function OrderLane({ title, items, onComplete, onNotify, onChat,}: { title: string; items: typeof initialOrders; onComplete: (id: string) => void; onNotify: (value: string) => void; onChat: () => void;}) { return (    <section className="rounded-2xl border-[#dfe4d6] bg-[#fffdf5] p-5">      <div className="flex items-center justify-between">        <h3 className="font-black text-[#20352b]">{title}</h3>        <span className="rounded-full bg-[#eaf1e4] px-2 py-1 text-[10px] font-black text-[#4f813f]">          {items.length}        </span>      </div>
      <div className="mt-4 space-y-3">        {items.map((order) => (          <div            key={order.id}            className="rounded-xl border-[#dfe7d9] bg-white p-4"          >            <div className="flex items-start justify-between gap-3">              <div>                <p className="text-xs font-black text-[#4f813f]">                  {order.id} · {order.name}                </p>                <p className="mt-2 text-sm font-bold text-[#20352b]">                  {order.items}                </p>              </div>
              <span className="rounded-full bg-[#f7edd3] px-2 py-1 text-[10px] font-black text-[#9a741d]">                {order.service}              </span>            </div>
            <div className="mt-4 flex items-center justify-between border-t border-[#edf1e9] pt-3">              <span className="font-black text-[#4f813f]">                {order.total}              </span>
              <div className="flex gap-1.5">                <Button                  onClick={onChat}                  className="size-8 rounded-lg bg-[#eaf1e4] p-0 text-[#4f813f] shadow-none hover:bg-[#dfeeda]"                >                  <MessageCircle size={15} />                </Button>
                <Button                  onClick={() => onNotify("تم تجهيز رسالة واتساب للطلب")}                  className="size-8 rounded-lg bg-[#eaf1e4] p-0 text-[#4f813f] shadow-none hover:bg-[#dfeeda]"                >                  <Link2 size={15} />                </Button>
                <Button                  onClick={() => onComplete(order.id)}                  className="h-8 rounded-lg bg-[#3f7440] px-3 text-[11px] font-black text-white shadow-none hover:bg-[#356436]"                >                  {title === "جديدة" ? "استلام" : "إنهاء"}                </Button>              </div>            </div>          </div>        ))}
        {!items.length && (          <div className="rounded-xl border-dashed border-[#cbd8c2] p-8 text-center text-sm text-[#849284]">            لا توجد طلبات هنا الآن.          </div>        )}      </div>    </section> );}
function Products({ products, onToggle, onNotify,}: { products: typeof initialProducts; onToggle: (id: string, status: string) => void; onNotify: (value: string) => void;}) { return (    <>      <PageHeading        eyebrow="المنتجات والمخزون"        title="حدّثي الرف من مكان واحد"        copy="تمييز وصل اليوم، إيقاف الصنف، وإضافة مجموعة منتجات دفعة واحدة."        action={          <Button            onClick={() => onNotify("تم فتح الإدخال الجماعي")}            className="h-10 rounded-xl bg-[#3f7440] px-4 text-xs font-black text-white shadow-none hover:bg-[#356436]"          >            <Plus size={15} />            إدخال جماعي          </Button>        }      />
      <div className="mt-7 rounded-2xl border-[#dfe4d6] bg-[#fffdf5] p-5">        <div className="grid gap-3 sm:grid-cols-2">          {products.map((product) => (            <div              key={product.id}              className="flex items-center gap-3 rounded-xl border-[#dfe7d9] bg-white p-4"            >              <span                className={`flex size-10 items-center justify-center rounded-xl ${                  product.status === "وصل اليوم"                    ? "bg-[#eaf1e4] text-[#4f813f]"                    : product.status === "غير متوفر"                      ? "bg-[#f8e3e7] text-[#a15e55]"                      : "bg-[#f7edd3] text-[#9a741d]"                }`}              >                <Package size={17} />              </span>
              <div className="min-w-0 flex-1">                <p className="font-black text-[#20352b]">{product.name}</p>                <p className="mt-1 text-xs text-[#849284]">                  {product.price} ر.س / {product.unit}                </p>              </div>
              <div className="flex flex-wrap justify-end gap-1">                <Button                  onClick={() => onToggle(product.id, "متوفر")}                  className="h-8 rounded-lg bg-transparent px-2 text-[10px] font-black text-[#4f813f] shadow-none hover:bg-[#eaf1e4]"                >                  متوفر                </Button>
                <Button                  onClick={() => onToggle(product.id, "وصل اليوم")}                  className="h-8 rounded-lg bg-transparent px-2 text-[10px] font-black text-[#9a741d] shadow-none hover:bg-[#f7edd3]"                >                  وصل اليوم                </Button>
                <Button                  onClick={() => onToggle(product.id, "غير متوفر")}                  className="h-8 rounded-lg bg-transparent px-2 text-[10px] font-black text-[#a15e55] shadow-none hover:bg-[#f8e3e7]"                >                  نفد                </Button>              </div>            </div>          ))}        </div>      </div>    </> );}
function Location({ sellerMode, setSellerMode, onNotify,}: { sellerMode: string; setSellerMode: (value: string) => void; onNotify: (value: string) => void;}) { return (    <>      <PageHeading        eyebrow="الموقع والساعات"        title="خلّي الوصول واضحاً"        copy="حددي إذا كنت ثابتاً أو متجولاً، ودعي العميل يعرف أين يلتقي بك."        action={          <Button            onClick={() => onNotify("تم حفظ الموقع والساعات")}            className="h-10 rounded-xl bg-[#3f7440] px-4 text-xs font-black text-white shadow-none hover:bg-[#356436]"          >            حفظ التغييرات            <Check size={15} />          </Button>        }      />
      <div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px]">        <section className="rounded-2xl border-[#dfe4d6] bg-[#fffdf5] p-5">          <p className="text-sm font-black text-[#20352b]">نوع البائع</p>
          <div className="mt-4 grid gap-3 sm:grid-cols-2">            <Button              onClick={() => setSellerMode("ثابت")}              className={`h-auto min-w-0 flex-col items-start gap-2 rounded-xl border p-4 text-right shadow-none ${                sellerMode === "ثابت"                  ? "border-[#5d914e] bg-[#eaf1e4]"                  : "border-[#dfe7d9] bg-white hover:bg-[#f0f5ec]"              }`}            >              <Store size={18} className="text-[#4f813f]" />              <span className="font-black">بائع ثابت</span>              <span className="text-xs font-normal text-[#849284]">                لديك موقع معروف يستلم منه العميل.              </span>            </Button>
            <Button              onClick={() => setSellerMode("متجول")}              className={`h-auto min-w-0 flex-col items-start gap-2 rounded-xl border p-4 text-right shadow-none ${                sellerMode === "متجول"                  ? "border-[#5d914e] bg-[#eaf1e4]"                  : "border-[#dfe7d9] bg-white hover:bg-[#f0f5ec]"              }`}            >              <Truck size={18} className="text-[#4f813f]" />              <span className="font-black">بائع متجول</span>              <span className="text-xs font-normal text-[#849284]">                يظهر اقترابك للعميل عبر الموقع.              </span>            </Button>          </div>
          <label className="mt-5 block text-xs font-bold text-[#647463]">            عنوان الموقع أو وصف المسار            <Input              defaultValue="سوق الحي، بوابة 2"              className="mt-2 h-11 border-[#d4dfcc] bg-white"            />          </label>
          <div className="mt-5 grid gap-3 sm:grid-cols-2">            <label className="text-xs font-bold text-[#647463]">              يفتح من              <Input                defaultValue="08:00"                type="time"                className="mt-2 h-11 border-[#d4dfcc] bg-white"              />            </label>
            <label className="text-xs font-bold text-[#647463]">              يغلق عند              <Input                defaultValue="22:00"                type="time"                className="mt-2 h-11 border-[#d4dfcc] bg-white"/>            </label>          </div>        </section>
        <section className="rounded-2xl bg-[#20352b] p-5 text-white">          <div className="flex items-center gap-2 text-[#cbe4b8]">            <LocateFixed size={18} />            <span className="text-xs font-bold tracking-[0.13em]">              الموقع المباشر            </span>          </div>
          <h3 className="mt-3 text-xl font-black">            {sellerMode === "متجول" ? "يظهر عند الاقتراب" : "نقطة الاستلام"}          </h3>
          <div className="mt-5 flex h-48 items-center justify-center rounded-xl border-white/10 bg-[#29473b]">            <div className="text-center text-xs text-[#c4dcc1]">              <MapPin size={28} className="mx-auto mb-2 text-[#cbe4b8]" />              معاينة الخريطة            </div>          </div>
          <Button            onClick={() => onNotify("تم تحديث موقعك الآن")}            className="mt-4 h-10 w-full rounded-xl bg-[#d7e9c9] text-xs font-black text-[#27472c] shadow-none hover:bg-white"          >            تحديث موقعي الآن            <LocateFixed size={15} />          </Button>        </section>      </div>    </> );}
function Payment({ onNotify }: { onNotify: (value: string) => void }) { return (    <>      <PageHeading        eyebrow="الدفع المباشر"        title="اجعل التحويل بسيطاً"        copy="التعليمات تظهر بعد إرسال الطلب، مع إمكانية نسخها أو مشاركتها."        action={          <Button            onClick={() => onNotify("تم حفظ بيانات الدفع")}            className="h-10 rounded-xl bg-[#3f7440] px-4 text-xs font-black text-white shadow-none hover:bg-[#356436]"          >            حفظ البيانات            <Check size={15} />          </Button>        }      />
      <div className="mt-7 grid gap-6 lg:grid-cols-2">        <section className="rounded-2xl border-[#dfe4d6] bg-[#fffdf5] p-5">          <div className="grid gap-4 sm:grid-cols-2">            <Field label="اسم البنك" value="STC Bank" />            <Field label="اسم المستفيد" value="خضارنا1" />          </div>
          <Field            label="تعليمات التحويل"            value="بعد التحويل أرسل صورة الإيصال على واتساب."          />
          <div className="mt-5 flex gap-2">            <Button              onClick={() => onNotify("تم نسخ تعليمات الدفع")}              className="h-10 rounded-xl border-[#d4dfcc] bg-white text-xs font-bold text-[#5f705f] shadow-none hover:bg-[#eef4e9]"            >              <Copy size={15} />              نسخ            </Button>
            <Button              onClick={() => onNotify("تم تجهيز رابط الدفع")}              className="h-10 rounded-xl border-[#d4dfcc] bg-white text-xs font-bold text-[#5f705f] shadow-none hover:bg-[#eef4e9]"            >              <Link2 size={15} />              مشاركة            </Button>          </div>        </section>
        <section className="rounded-2xl bg-[#20352b] p-5 text-white">          <p className="text-xs font-bold tracking-[0.13em] text-[#cbe4b8]">            ما يراه العميل          </p>
          <div className="mt-5 rounded-xl bg-[#fffdf5] p-4 text-right text-sm text-[#20352b]">            <p className="font-black">الدفع عند الاستلام أو التحويل المباشر</p>            <p className="mt-3 text-xs leading-6 text-[#758374]">              بعد تحويل المبلغ، أرسل صورة الإيصال إلى خضارنا1 لتأكيد الطلب.            </p>          </div>        </section>      </div>    </> );}
function Tools({ flash, setFlash, onNotify,}: { flash: string; setFlash: (value: string) => void; onNotify: (value: string) => void;}) { return (    <>      <PageHeading        eyebrow="أدوات المشاركة"        title="خلّي الوصول أسهل"        copy="QR، عرض سريع، وروابط جاهزة لمشاركة متجر خضارنا1."        action={          <Button            onClick={() => onNotify("تم حفظ الأدوات")}            className="h-10 rounded-xl bg-[#3f7440] px-4 text-xs font-black text-white shadow-none hover:bg-[#356436]"          >            حفظ الأدوات            <Check size={15} />          </Button>        }      />
      <div className="mt-7 grid gap-6 md:grid-cols-2">        <section className="rounded-2xl border-[#dfe4d6] bg-[#fffdf5] p-5">          <div className="flex items-center gap-2">            <KhudaranaMark size="sm" />            <Grid2X2 size={18} className="text-[#4f813f]" />            <h3 className="font-black text-[#20352b]">ملصق QR</h3>          </div>
          <p className="mt-2 text-sm leading-6 text-[#758374]">            أنشئ ملصقاً يفتح صفحة خضارنا1 مباشرة عند مسحه.          </p>
          <div className="mx-auto mt-5 flex size-36 items-center justify-center border-8 border-[#20352b] bg-white text-center text-xs font-black text-[#20352b]">            QR            <br />            خضارنا1          </div>
          <Button            onClick={() => onNotify("تم تجهيز ملصق QR للطباعة")}            className="mt-5 h-10 w-full rounded-xl border-[#d4dfcc] bg-white text-xs font-black text-[#4f813f] shadow-none hover:bg-[#eef4e9]"          >            <FileText size={15} />            تجهيز للطباعة          </Button>        </section>
        <section className="rounded-2xl border-[#dfe4d6] bg-[#fffdf5] p-5">          <div className="flex items-center gap-2">            <SparklesIcon />            <h3 className="font-black text-[#20352b]">عرض الفلاش</h3>          </div>
          <p className="mt-2 text-sm leading-6 text-[#758374]">            رسالة قصيرة تظهر أعلى المتجر وتغيّرها في ثوانٍ.          </p>
          <Textarea            value={flash}            onChange={(event) => setFlash(event.target.value)}            className="mt-5 min-h-24 border-[#d4dfcc] bg-white"          />
          <Button            onClick={() => onNotify("تم نشر العرض الفلاش")}            className="mt-4 h-10 w-full rounded-xl bg-[#3f7440] text-xs font-black text-white shadow-none hover:bg-[#356436]"          >            نشر العرض            <ArrowLeft size={15} />          </Button>        </section>      </div>    </> );}
function Chat({ onClose, onNotify,}: { onClose: () => void; onNotify: (value: string) => void;}) { return (    <div className="fixed bottom-5 left-5 z-50 w-[min(360px,calc(100vw-2rem))] overflow-hidden rounded-2xl border-[#d4dfcc] bg-[#fffdf5] shadow-2xl">      <div className="flex items-center justify-between bg-[#20352b] p-4 text-white">        <div>          <p className="font-black">دردشة خضارنا1</p>          <p className="mt-1 text-[11px] text-[#c4dcc1]">            نورة متصلة الآن          </p>        </div>
        <Button          onClick={onClose}          className="size-8 rounded-lg bg-white/10 p-0 text-white shadow-none hover:bg-white/20"        >          <X size={15} />        </Button>      </div>
      <div className="space-y-3 p-4">        <div className="rounded-xl bg-[#eaf1e4] p-3 text-xs leading-5 text-[#315534]">          هل يوجد نعناع وصل اليوم؟        </div>
        <div className="mr-8 rounded-xl bg-[#f4eee7] p-3 text-xs leading-5 text-[#6d7b6d]">          نعم، نحدثه الآن في الرف.        </div>
        <div className="flex gap-2">          <Input            placeholder="اكتب رسالة..."            className="h-9 border-[#d4dfcc] bg-white text-xs"          />
          <Button            onClick={() => onNotify("تم إرسال الرسالة")}            className="size-9 rounded-lg bg-[#3f7440] p-0 text-white shadow-none"          >            <ArrowLeft size={15} />          </Button>        </div>      </div>    </div> );}
function PageHeading({ eyebrow, title, copy, action,}: { eyebrow: string; title: string; copy: string; action: React.ReactNode;}) { return (    <div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end">      <div>        <p className="text-xs font-bold tracking-[0.16em] text-[#5b7d48]">          {eyebrow}        </p>        <h2 className="mt-2 text-3xl font-black tracking-[-0.05em] text-[#20352b] sm:text-4xl">          {title}        </h2>        <p className="mt-2 max-w-2xl text-sm leading-6 text-[#758374]">          {copy}        </p>      </div>
      {action}    </div> );}
function Metric({ label, value, hint, tone,}: { label: string; value: string; hint: string; tone: "green" | "blue" | "gold" | "olive";}) { const styles = {    green: "bg-[#eaf1e4] text-[#4f813f]",    blue: "bg-[#e3eef0] text-[#4a7a83]",    gold: "bg-[#f7edd3] text-[#9a741d]",    olive: "bg-[#edf0dc] text-[#687638]", };
 return (    <div className="rounded-2xl border-[#dfe4d6] bg-[#fffdf5] p-4">      <p className="text-xs font-bold text-[#849284]">{label}</p>
      <div className="mt-2 flex items-end justify-between">        <span className="text-3xl font-black text-[#20352b]">{value}</span>        <span          className={`rounded-full px-2 py-1 text-[10px] font-black ${styles[tone]}`}        >          {hint}        </span>      </div>    </div> );}
function Field({ label, value }: { label: string; value: string }) { return (    <label className="mb-4 block text-xs font-bold text-[#647463]">      {label}      <Input        defaultValue={value}        className="mt-2 h-11 border-[#d4dfcc] bg-white"      />    </label> );}
function SparklesIcon() { return (    <span className="flex size-8 items-center justify-center rounded-lg bg-[#eaf1e4] text-[#4f813f]">      <Settings2 size={17} />    </span> );}
import { KhudaranaMark } from "@/components/khudarana-mark";