import { CORPORATE_PRODUCT_COMPLIANCE_SECTIONS } from '@/config/corporateProductCompliance';
import {
  PLATFORM_DIGITAL_PRODUCT_INTRO_BADGE,
  PLATFORM_DIGITAL_PRODUCT_INTRO_PARAGRAPHS,
  PLATFORM_DIGITAL_PRODUCT_INTRO_TITLE,
} from '@/config/platformGrowthNarrative';

export const HONOR_BOARD_MANIFESTO_BADGE = PLATFORM_DIGITAL_PRODUCT_INTRO_BADGE;

export const HONOR_BOARD_MANIFESTO_TITLE = PLATFORM_DIGITAL_PRODUCT_INTRO_TITLE;

export const HONOR_BOARD_MANIFESTO_PARAGRAPHS = PLATFORM_DIGITAL_PRODUCT_INTRO_PARAGRAPHS;

export const HONOR_BOARD_CORE_VALUES = CORPORATE_PRODUCT_COMPLIANCE_SECTIONS;

export const HONOR_BOARD_PROFESSIONAL_COMMITMENT_LEAD =
  'بالانضمام إلى شبكة حلاق ماب كشريك B2B، تُقرّ بامتثال منشأتك للأنظمة المعمول بها وتلتزم بمعايير الجودة والشفافية التي تحكم منتجاتنا الرقمية.';
