/**
 * Copyright © 2026 HalaqMap. All Rights Reserved.
 *
 * واجهة النشاط الحيّة — نصوص عرض صفحة العميلة في حلانا1.
 */

export const STORE_HALANA_ACTIVITY_COPY = {
  doctrineAr: 'واجهة النشاط الحيّة',
  statusOpenAr: 'تستقبل الطلبات',
  statusPausedAr: 'اعتذار مؤقت عن استقبال الطلبات',
  statusLimitedAr: 'مواعيد محدودة',
  browseWorksAr: 'استعرضي الأعمال',
  startOrderAr: 'ابدئي طلباً',
  orderSimilarAr: 'اطلبي تنفيذاً مشابهاً',
  orderThisAr: 'اطلبي هذا الخيار',
  orderInspiredAr: 'أريد شيئاً قريباً من هذا',
  trustStrip: [
    'تنفيذ حسب الطلب',
    'مراجعة قبل تثبيت الموعد',
    'التواصل والدفع مع المتخصصة',
    'لا عمولة على قيمة الطلب',
  ] as const,
  explorerTitleAr: 'وش المناسبة؟ نقرّب لك الاختيار',
  tabs: {
    home: 'الرئيسية',
    ready: 'جاهز للطلب',
    works: 'من التنفيذ',
    about: 'عن المتخصصة',
  } as const,
  featuredTitleAr: 'مختارات اليوم',
  featuredLeadAr: 'أعمال مختارة للإلهام — اضغطي للتفاصيل ثم ابدئي طلباً مشابهاً.',
  readyTitleAr: 'اختيارات جاهزة للطلب',
  readyLeadAr: 'ما صنّفته المتخصصة كمتاح للطلب — السعر والموعد يُراجعان قبل التثبيت.',
  readyPricingAr: 'يُحدد بعد مراجعة التفاصيل',
  readyPreorderAr: 'يحتاج طلباً مسبقاً',
  worksTitleAr: 'من تنفيذ المتخصصة',
  worksLeadAr: 'معرض إلهام — كل عمل يمكن أن يصبح نقطة بداية لطلبك.',
  liveReadyBannerAr: (line: string) => `متاح الآن · ${line}`,
  policySummaryTitleAr: 'سياسة الطلب باختصار',
  policySummary: [
    'أرسلي تفاصيل طلبك من صفحة الطلب.',
    'تراجع المتخصصة الموعد والتنفيذ.',
    'يصلك عرض السعر وطريقة التأكيد.',
    'يُثبت الموعد بعد الإجراء المعتمد لدى المتخصصة.',
  ] as const,
  policyFullAr: 'قراءة سياسة الطلب كاملة',
  videoTitleAr: 'شاهدي التفاصيل عن قرب',
  videoPlayAr: 'تشغيل',
  flavorsPreviewAr: 'نكهات متوفرة هذا الأسبوع',
  flavorsOrderHintAr: 'اختيار النكهات يتم داخل صفحة الطلب.',
  stickyBrowseAr: 'استعرضي الأعمال',
  stickyOrderAr: 'ابدئي طلباً',
  stickyContinueAr: 'أكملي طلبك',
  stickyInspiredAr: 'ابدئي طلباً مستوحى من اختيارك',
  workSheetCloseAr: 'إغلاق',
  workSheetIncludesAr: 'ما يظهر في هذا العمل',
  orderSteps: {
    intent: 'نوع الطلب',
    customize: 'التخصيص',
    schedule: 'الموعد والتواصل',
    review: 'المراجعة',
  } as const,
  orderIntentTitleAr: 'ماذا تريدين؟',
  orderFromWorkAr: 'طلب من عمل معروض',
  orderInspiredChoiceAr: 'تنفيذ قريب من صورة',
  orderFreshAr: 'طلب خاص من البداية',
  orderFlavorsTitleAr: 'النكهات والحشوات',
  orderFlavorsLeadAr: 'اختاري ما يناسبك — يمكن تعديله قبل بدء التجهيز.',
  orderDateWarnAr: 'التاريخ المطلوب يخضع لمراجعة المتخصصة قبل تثبيت الطلب.',
  orderReviewTitleAr: 'ملخص الطلب',
  orderReviewWarnAr: 'الإرسال لا يعني قبول الطلب أو تثبيت الموعد.',
  orderNextAr: 'التالي',
  orderBackAr: 'رجوع',
  orderSendAr: 'إرسال الطلب للمراجعة',
} as const;
