"use client";
import Image from "next/image";import { useEffect, useMemo, useState } from "react";import { Check, ChevronLeft, Clock3, MapPin, Minus, Plus, Search, ShoppingBag, Store, Truck, X,} from "lucide-react";import { TabkhatnaMark } from "@/components/tabkhatna-mark";import { Button } from "@/components/ui/button";import { Input } from "@/components/ui/input";
const dishes = [ { id: "dish-1", name: "كبسة دجاج بيتية", unit: "تكفي 4 أشخاص", price: 68, category: "وجبات اليوم", image: "/tabkhatna/dish-kabsa.webp" }, { id: "dish-2", name: "صينية مكرونة بالبشاميل", unit: "تكفي 6 أشخاص", price: 82, category: "وجبات اليوم", image: "/tabkhatna/dish-pasta.webp" }, { id: "dish-3", name: "محشي ورق عنب", unit: "صحن عائلي", price: 54, category: "أطباق جانبية", image: "/tabkhatna/dish-grape-leaves.webp" }, { id: "dish-4", name: "سمبوسة مشكلة", unit: "30 قطعة", price: 36, category: "مقبلات", image: "/tabkhatna/dish-samosa.webp" }, { id: "dish-5", name: "سلطة فتوش", unit: "صحن كبير", price: 22, category: "أطباق جانبية", image: "/tabkhatna/dish-fattoush.webp" }, { id: "dish-6", name: "حلى كاسات", unit: "12 كاسة", price: 42, category: "حلويات", image: "/tabkhatna/dish-dessert.webp" },];
const categories = ["الكل", "وجبات اليوم", "أطباق جانبية", "مقبلات", "حلويات"];
type Dish = (typeof dishes)[number];type Cart = Record<string, number>;
export default function TabkhatnaStorefront() { const [query, setQuery] = useState(""); const [category, setCategory] = useState("الكل"); const [cart, setCart] = useState<Cart>({}); const [cartOpen, setCartOpen] = useState(false); const [service, setService] = useState<"delivery" | "pickup">("delivery"); const [notice, setNotice] = useState("");
 useEffect(() => {    const saved = window.localStorage.getItem("tabkhatna1-cart");    if (!saved) return;
    try {      const stored = JSON.parse(saved) as { cart: Cart; expires: number };      if (stored.expires > Date.now()) setCart(stored.cart);      else window.localStorage.removeItem("tabkhatna1-cart");    } catch {      window.localStorage.removeItem("tabkhatna1-cart");    } }, []);
 useEffect(() => {    if (Object.keys(cart).length > 0) {      window.localStorage.setItem(        "tabkhatna1-cart",        JSON.stringify({          cart,          expires: Date.now() + 7 * 24 * 60 * 60 * 1000,        }),      );    } }, [cart]);
 const filteredDishes = useMemo(    () =>      dishes.filter((dish) => {        const matchesCategory =          category === "الكل" || dish.category === category;        return matchesCategory && `${dish.name} ${dish.unit}`.includes(query);      }),    [category, query], );
 const cartItems = dishes.filter((dish) => cart[dish.id]); const itemCount = cartItems.reduce(    (total, dish) => total + cart[dish.id],    0, ); const subtotal = cartItems.reduce(    (total, dish) => total + dish.price * cart[dish.id],    0, ); const deliveryFee = service === "delivery" ? 10 : 0; const total = subtotal + deliveryFee;
 function notify(message: string) {    setNotice(message);    window.setTimeout(() => setNotice(""), 2200); }
 function updateCart(dish: Dish, delta: number) {    setCart((current) => {      const nextQuantity = Math.max(0, (current[dish.id] ?? 0) + delta);      const nextCart = { ...current };
      if (nextQuantity) nextCart[dish.id] = nextQuantity;      else delete nextCart[dish.id];
      return nextCart;    }); }
 return (    <main dir="rtl" className="min-h-dvh bg-orange-50 text-stone-950">      <header className="border-b border-orange-100 bg-orange-700 text-white">        <div className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-4 px-4 py-3 sm:px-8">          <div className="flex min-w-0 items-center gap-3">            <TabkhatnaMark inverse />            <div className="min-w-0">              <p className="text-[11px] font-bold tracking-[0.18em] text-orange-100">                جار الحي              </p>              <p className="truncate text-xl font-black">طبختنا1</p>            </div>          </div>
          <div className="order-3 flex w-full min-w-0 items-center gap-2 rounded-xl bg-white p-1 text-stone-800 sm:order-none sm:max-w-xl">            <Search size={18} className="mx-2 shrink-0 text-stone-400" />            <Input              value={query}              onChange={(event) => setQuery(event.target.value)}              placeholder="ابحث عن كبسة، حلويات، مقبلات..."              className="h-10 min-w-0 border-0 bg-transparent text-sm shadow-none focus-visible:ring-0"            />            <Button              onClick={() =>                notify(                  query                    ? `نتائج البحث عن: ${query}`                    : "اكتب اسم الطبق للبحث",                )              }              className="h-10 shrink-0 rounded-lg bg-amber-500 px-4 text-sm font-black text-white hover:bg-amber-600"            >              بحث            </Button>          </div>
          <Button            onClick={() => setCartOpen(true)}            className="h-11 rounded-xl bg-white px-4 text-sm font-black text-orange-800 shadow-none hover:bg-orange-50"          >            <ShoppingBag size={17} />            السلة            {itemCount > 0 && (              <span className="flex size-6 items-center justify-center rounded-full bg-amber-500 text-xs text-white">                {itemCount}              </span>            )}          </Button>        </div>      </header>
      <div className="mx-auto max-w-[1440px] px-4 pb-32 sm:px-8">        <section className="grid gap-6 border-b border-orange-100 py-6 lg:grid-cols-[minmax(0,1fr)_280px] lg:items-center">          <div>            <div className="mb-3 flex items-center gap-2 text-xs font-bold text-orange-700">              <span className="h-px w-8 bg-amber-500" />              طبخ البيت يصل لبابك            </div>
            <h1 className="max-w-2xl text-4xl font-black tracking-tight text-stone-950 sm:text-6xl">              أكل البيت،              <br />              <span className="text-orange-700">بطعم يحكي.</span>            </h1>
            <p className="mt-4 max-w-xl text-base leading-8 text-stone-600">              أطباق منزلية تُطبخ بعناية في مطابخ الحي. اختَر وجبتك، حدد الكمية،              وخلي طبختنا تهتم بالباقي.            </p>
            <div className="mt-5 flex-wrap gap-3">              <div className="flex items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-bold text-stone-600 shadow-sm">                <Truck size={15} className="text-amber-500" />                توصيل في نفس اليوم              </div>
              <div className="flex items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-bold text-stone-600 shadow-sm">                <Store size={15} className="text-orange-700" />                طبخ منزلي              </div>            </div>          </div>
          <div className="rounded-2xl border-orange-100 bg-white p-4 shadow-sm">            <div className="flex items-center justify-between gap-3">              <div className="flex min-w-0 items-center gap-3">                <TabkhatnaMark size="sm" />                <div className="min-w-0">                  <p className="text-xs font-bold text-stone-500">                    حالة طبختنا1                  </p>                  <p className="mt-1 truncate font-black text-stone-950">                    تستقبل الطلبات                  </p>                </div>              </div>
              <span className="size-3 shrink-0 rounded-full bg-emerald-500" />            </div>
            <div className="mt-4 space-y-2 text-xs text-stone-600">              <p className="flex items-center gap-2">                <Clock3 size={14} className="text-orange-700" />                وجبات اليوم جاهزة للحجز              </p>              <p className="flex items-center gap-2">                <MapPin size={14} className="text-orange-700" />                حي الروضة · مطبخ منزلي              </p>            </div>
            <Button              onClick={() => notify("السلة محفوظة لمدة 7 أيام")}              className="mt-4 h-10 w-full rounded-lg bg-orange-50 text-xs font-black text-orange-800 shadow-none hover:bg-orange-100"            >              حفظ السلة 7 أيام              <Check size={15} />            </Button>          </div>        </section>
        <div className="grid gap-6 py-6 lg:grid-cols-[190px_minmax(0,1fr)]">          <aside className="lg:sticky lg:top-4 lg:h-fit">            <div className="flex items-center justify-between">              <p className="text-xs font-black tracking-[0.16em] text-stone-500">                الأقسام              </p>              <span className="text-xs text-stone-400">                {filteredDishes.length} أطباق              </span>            </div>
            <div className="mt-3 grid-cols-2 gap-2 lg:grid-cols-1">              {categories.map((item) => (                <Button                  key={item}                  onClick={() => setCategory(item)}                  className={`h-11 min-w-0 justify-start rounded-lg px-3 text-sm font-bold shadow-none ${                    category === item                      ? "bg-orange-700 text-white hover:bg-orange-800"                      : "bg-white text-stone-600 hover:bg-orange-50"                  }`}                >                  <span className="truncate">{item}</span>                  <ChevronLeft size={15} className="mr-auto shrink-0" />                </Button>              ))}            </div>          </aside>
          <section id="shelf" className="min-w-0">            <div className="mb-4 flex-wrap items-end justify-between gap-3">              <div>                <p className="text-xs font-bold text-amber-600">رف اليوم</p>                <h2 className="mt-1 text-2xl font-black text-stone-950">                  اختيارات من مطبخ البيت                </h2>              </div>
              <p className="text-xs text-stone-500">                أضف الكمية مباشرة من الرف              </p>            </div>
            <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">              {filteredDishes.map((dish) => (                <article                  key={dish.id}                  className="min-w-0 rounded-2xl border-orange-100 bg-white p-3 shadow-sm"                >                  <div className="relative aspect-square overflow-hidden rounded-xl bg-orange-50">                    <Image                      src={dish.image}                      alt={dish.name}                      fill                      sizes="(min-width: 1280px) 25vw, (min-width: 640px) 40vw, 80vw"                      className="object-cover"                    />                  </div>
                  <div className="min-w-0 pt-3">                    <p className="text-[10px] font-bold text-amber-600">                      {dish.category}                    </p>                    <h3 className="mt-1 truncate text-sm font-black">                      {dish.name}                    </h3>                    <p className="mt-1 text-xs text-stone-500">{dish.unit}</p>
                    <div className="mt-2 flex items-center justify-between gap-2">                      <strong className="text-lg font-black text-orange-800">                        {dish.price.toFixed(2)}{" "}                        <span className="text-[10px]">ر.س</span>                      </strong>
                      <div className="flex shrink-0 items-center rounded-lg border border-orange-100">                        <Button                          aria-label={`تقليل ${dish.name}`}                          onClick={() => updateCart(dish, -1)}                          className="size-8 rounded-none bg-transparent p-0 text-stone-500 shadow-none hover:bg-orange-50"                        >                          <Minus size={14} />                        </Button>
                        <span className="flex h-8 min-w-7 items-center justify-center text-xs font-black">                          {cart[dish.id] ?? 0}                        </span>
                        <Button                          aria-label={`إضافة ${dish.name}`}                          onClick={() => updateCart(dish, 1)}                          className="size-8 rounded-none bg-amber-500 p-0 text-white shadow-none hover:bg-amber-600"                        >                          <Plus size={14} />                        </Button>                      </div>                    </div>                  </div>                </article>              ))}            </div>
            {filteredDishes.length === 0 && (              <div className="rounded-2xl border-dashed border-orange-200 bg-white p-12 text-center text-sm text-stone-500">                لا توجد نتائج بهذا الاسم في هذا القسم.              </div>            )}
            <div className="mt-6 overflow-hidden rounded-2xl border-orange-100 bg-white">              <Image                src="/tabkhatna/lower-dishes.webp"                alt="أطباق منزلية جاهزة"                width={1200}                height={675}                className="h-32 w-full object-cover sm:h-44"              />            </div>          </section>        </div>      </div>
      {itemCount > 0 && (        <Button          onClick={() => setCartOpen(true)}          className="fixed bottom-4 left-4 right-4 z-30 flex h-auto items-center justify-between rounded-xl bg-orange-950 px-5 py-4 text-right text-white shadow-xl sm:left-auto sm:right-8 sm:w-[360px]"        >          <span>            <span className="block text-xs text-orange-200">              {itemCount} عناصر في السلة            </span>            <strong className="mt-1 block text-lg">              {total.toFixed(2)} ر.س            </strong>          </span>
          <span className="flex items-center gap-2 rounded-lg bg-amber-500 px-4 py-2 text-sm font-black">            عرض السلة            <ChevronLeft size={16} />          </span>        </Button>      )}
      {cartOpen && (        <div          className="fixed inset-0 z-50 bg-stone-950/40"          onClick={() => setCartOpen(false)}        >          <aside            className="absolute inset-y-0 left-0 flex w-full max-w-md flex-col bg-white p-5 shadow-2xl"            onClick={(event) => event.stopPropagation()}          >            <div className="flex items-center justify-between border-b border-orange-100 pb-4">              <div className="flex items-center gap-3">                <TabkhatnaMark size="sm" />                <div>                  <p className="text-xs font-bold text-amber-600">                    السلة محفوظة 7 أيام                  </p>                  <h2 className="mt-1 text-2xl font-black">                    سلة المشتريات                  </h2>                </div>              </div>
              <Button                onClick={() => setCartOpen(false)}                className="size-9 rounded-lg bg-orange-50 p-0 text-stone-700 shadow-none hover:bg-orange-100"              >                <X size={17} />              </Button>            </div>
            <div className="flex-1 space-y-3 overflow-y-auto py-5">              {cartItems.map((dish) => (                <div                  key={dish.id}                  className="flex min-w-0 items-center gap-3 rounded-xl border-orange-100 p-3"                >                  <Image                    src={dish.image}                    alt=""                    width={64}                    height={64}                    className="size-16 shrink-0 rounded-lg bg-orange-50 object-cover"                  />
                  <div className="min-w-0 flex-1">                    <p className="truncate text-sm font-black">{dish.name}</p>                    <p className="mt-1 text-xs text-stone-500">                      {dish.price.toFixed(2)} ر.س · {dish.unit}                    </p>
                    <div className="mt-2 flex items-center gap-2">                      <Button                        onClick={() => updateCart(dish, -1)}                        className="size-7 rounded-md bg-orange-50 p-0 text-stone-700 shadow-none"                      >                        <Minus size={13} />                      </Button>
                      <span className="text-xs font-black">                        {cart[dish.id]}                      </span>
                      <Button                        onClick={() => updateCart(dish, 1)}                        className="size-7 rounded-md bg-amber-500 p-0 text-white shadow-none"                      >                        <Plus size={13} />                      </Button>                    </div>                  </div>                </div>              ))}
              {cartItems.length === 0 && (                <p className="py-12 text-center text-sm text-stone-500">                  السلة فارغة، أضف ما تشتهيه من الرف.                </p>              )}            </div>
            <div className="border-t border-orange-100 pt-4">              <div className="mb-4 flex gap-2">                <Button                  onClick={() => setService("delivery")}                  className={`h-11 min-w-0 flex-1 rounded-lg text-xs font-black shadow-none ${                    service === "delivery"                      ? "bg-orange-700 text-white"                      : "bg-orange-50 text-stone-600"                  }`}                >                  <Truck size={15} />                  توصيل                </Button>
                <Button                  onClick={() => setService("pickup")}                  className={`h-11 min-w-0 flex-1 rounded-lg text-xs font-black shadow-none ${                    service === "pickup"                      ? "bg-orange-700 text-white"                      : "bg-orange-50 text-stone-600"                  }`}                >                  <Store size={15} />                  استلام                </Button>              </div>
              <div className="flex items-center justify-between text-sm text-stone-600">                <span>المجموع</span>                <strong className="text-lg font-black text-stone-950">                  {total.toFixed(2)} ر.س                </strong>              </div>
              <Button                onClick={() => {                  setCartOpen(false);                  notify("تم تجهيز السلة للمراجعة");                }}                className="mt-4 h-12 w-full rounded-xl bg-amber-500 text-sm font-black text-white shadow-none hover:bg-amber-600"              >                متابعة الطلب                <ChevronLeft size={17} />              </Button>            </div>          </aside>        </div>      )}
      {notice && (        <div className="fixed left-1/2 top-5 z-[60] -translate-x-1/2 rounded-full bg-stone-950 px-5 py-3 text-xs font-bold text-white shadow-xl">          {notice}        </div>      )}    </main> );}