-- =====================================================
-- المناوب الرقمي الذكي (Diamond B2B Add-on)
-- إعدادات المساعد، محفظة AI، توصيات، وعلامة ردود المناوبة
-- =====================================================

CREATE TABLE IF NOT EXISTS public.barber_digital_shift_config (
  barber_id UUID PRIMARY KEY REFERENCES public.barbers(id) ON DELETE CASCADE,
  assistant_display_name TEXT NOT NULL DEFAULT 'المناوب الرقمي',
  reply_delay_minutes INT NOT NULL DEFAULT 3 CHECK (reply_delay_minutes BETWEEN 1 AND 30),
  enabled BOOLEAN NOT NULL DEFAULT true,
  banner_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  gallery_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
  last_insights_refresh_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.barber_ai_wallet (
  barber_id UUID PRIMARY KEY REFERENCES public.barbers(id) ON DELETE CASCADE,
  balance_halalas INT NOT NULL DEFAULT 10000 CHECK (balance_halalas >= 0),
  total_spent_halalas INT NOT NULL DEFAULT 0 CHECK (total_spent_halalas >= 0),
  low_balance_threshold_halalas INT NOT NULL DEFAULT 3000 CHECK (low_balance_threshold_halalas >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.barber_ai_wallet_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  barber_id UUID NOT NULL REFERENCES public.barbers(id) ON DELETE CASCADE,
  amount_halalas INT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('credit', 'debit')),
  reason TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS barber_ai_wallet_tx_barber_created_idx
  ON public.barber_ai_wallet_transactions(barber_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.barber_ai_recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  barber_id UUID NOT NULL REFERENCES public.barbers(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN ('balance', 'banner', 'gallery', 'shift_chat')),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  priority INT NOT NULL DEFAULT 50 CHECK (priority BETWEEN 1 AND 100),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'dismissed', 'resolved')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS barber_ai_recommendations_barber_status_idx
  ON public.barber_ai_recommendations(barber_id, status, priority DESC, created_at DESC);

ALTER TABLE public.private_messages
  ADD COLUMN IF NOT EXISTS is_digital_shift_reply BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN public.private_messages.is_digital_shift_reply IS
  'true when the message was generated by المناوب الرقمي الذكي on behalf of the barber.';

-- Seed config + wallet for existing diamond barbers
INSERT INTO public.barber_digital_shift_config (barber_id)
SELECT b.id
FROM public.barbers b
WHERE b.tier = 'diamond'
ON CONFLICT (barber_id) DO NOTHING;

INSERT INTO public.barber_ai_wallet (barber_id)
SELECT b.id
FROM public.barbers b
WHERE b.tier = 'diamond'
ON CONFLICT (barber_id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.touch_barber_digital_shift_config_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_barber_digital_shift_config ON public.barber_digital_shift_config;
CREATE TRIGGER trg_touch_barber_digital_shift_config
  BEFORE UPDATE ON public.barber_digital_shift_config
  FOR EACH ROW EXECUTE FUNCTION public.touch_barber_digital_shift_config_updated_at();

CREATE OR REPLACE FUNCTION public.ensure_barber_digital_shift_on_diamond()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.tier = 'diamond' THEN
    INSERT INTO public.barber_digital_shift_config (barber_id)
    VALUES (NEW.id)
    ON CONFLICT (barber_id) DO NOTHING;
    INSERT INTO public.barber_ai_wallet (barber_id)
    VALUES (NEW.id)
    ON CONFLICT (barber_id) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ensure_barber_digital_shift_on_diamond ON public.barbers;
CREATE TRIGGER trg_ensure_barber_digital_shift_on_diamond
  AFTER INSERT OR UPDATE OF tier ON public.barbers
  FOR EACH ROW EXECUTE FUNCTION public.ensure_barber_digital_shift_on_diamond();

COMMENT ON TABLE public.barber_digital_shift_config IS 'Diamond add-on: المناوب الرقمي الذكي settings per barber.';
COMMENT ON TABLE public.barber_ai_wallet IS 'AI shift assistant prepaid balance (halalas) for automated customer replies.';
COMMENT ON TABLE public.barber_ai_recommendations IS 'Reactive insights table for the digital shift recommendations desk UI.';
